### ISSUE TITLE
Only transition the router

### ISSUE THREAD

**Issue by bjkippax** [duannx/vue-router-transition#1]
## Description of issue

When transitioning, the entire page transitions, rather than targeting just the router component.
I'd expect that only the portion of the page governed by the `router-view` would transition.

## Example

https://www.loom.com/share/57e1639e6660420f8f1b150dc762bfd7

**Comment by duannx** [comment]
@bjkippax The transition is done by CSS so you can add your custom CSS to achieve what you need.
The package is designed to transform the `router-view` only. However, some transitions are using fixed positions so it goes out of `router-view` 

I fixed it in #2 and published a new version of this package. But, I can not log in to my old npm account so the package can not be updated. I decided to create a new package [@duannx/vue-router-transition](https://www.npmjs.com/package/@duannx/vue-router-transition). Just remove your old package and use the new one. The problem should go. [Demo](https://duannx.github.io/vue-router-transition/)

Let me know if you are still facing any issues.
